# Generated by Django 5.2.1 on 2025-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("product", models.CharField(max_length=200)),
                (
                    "payment_slip",
                    models.FileField(blank=True, null=True, upload_to="payments/"),
                ),
            ],
        ),
    ]
